"""
src/models/train_hvt_gnn_v3.py

Train a baseline high_value_target (y_hvt) node classifier on a single PyG graph
generated by build_pyg_dataset.py.

- Model: simple Relational GCN (RGCNConv)
- Task: y_hvt (0/1) binary classification
- Inputs:
    * x           : [N, F]
    * edge_index  : [2, E]
    * edge_type   : [E] (0=hier, 1=finance, 2=comm, 3=ops, 4=ideo)
    * train/val/test_mask

Extras:
    - pos_weight option to handle class imbalance
"""

import argparse
import os
import random
import json

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.data import Data
from torch_geometric.nn import RGCNConv
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score


# -----------------------------
# Safe PyG loader (PyTorch >=2.6 friendly)
# -----------------------------
def load_pyg_data(path: str, map_location: str | torch.device = "cpu") -> Data:
    try:
        import torch.serialization
        torch.serialization.add_safe_globals([Data])
    except Exception:
        pass
    return torch.load(path, map_location=map_location, weights_only=False)


# -----------------------------
# Edge-attr transform utilities
# -----------------------------
def resolve_edge_attr_transform_np(
    ea: np.ndarray,
    mode: str = "auto",
    q: float = 0.99,
    thresh: float = 20.0,
) -> str:
    mode = (mode or "auto").lower()
    if mode in ("none", "raw"):
        return "none"
    if mode in ("log1p", "log"):
        return "log1p"
    ea = np.asarray(ea, dtype=np.float32).reshape(-1)
    ea = np.clip(ea, 0.0, None)
    if ea.size == 0:
        return "none"
    try:
        qq = float(np.quantile(ea, q))
    except Exception:
        qq = float(ea.max())
    mx = float(ea.max())
    return "log1p" if (qq > float(thresh) or mx > float(thresh)) else "none"


def transform_edge_attr_torch(w: torch.Tensor, transform: str) -> torch.Tensor:
    w = w.clamp(min=0.0)
    if transform == "log1p":
        return torch.log1p(w)
    return w


# -----------------------------
# Utility helpers
# -----------------------------

def augment_with_edge_attr(data: Data, edge_attr_transform: str = "none") -> Data:
    """
    Aggregate edge_attr (per-layer weights) to the node level and
    append [relation-wise aggregated weight] features to x.

    - data.edge_attr : [E, 1] or [E]
    - data.edge_type : [E]
    - data.edge_index: [2, E]
    """
    if not hasattr(data, "edge_attr") or data.edge_attr is None:
        print("[augment] data.edge_attr missing → skip")
        return data

    edge_attr = data.edge_attr
    if edge_attr.dim() == 1:
        edge_attr = edge_attr.unsqueeze(-1)
    edge_attr = edge_attr.float()          # [E, attr_dim] (assume attr_dim=1 for now)

    edge_index = data.edge_index
    edge_type = data.edge_type
    num_nodes = data.x.size(0)
    num_relations = int(edge_type.max().item()) + 1

    # 1) Stabilize with log1p + clamp
    w = torch.log1p(edge_attr[:, 0].clamp(min=0))  # avoid negatives

    one_hot_rel = F.one_hot(edge_type, num_classes=num_relations).float()
    weighted_rel = one_hot_rel * w.unsqueeze(-1)  # [E, R]

    agg = torch.zeros(num_nodes, num_relations, dtype=torch.float32)
    src, dst = edge_index

    agg.index_add_(0, src, weighted_rel)
    agg.index_add_(0, dst, weighted_rel)

    # 2) Normalize by degree to take the mean
    deg = torch.zeros(num_nodes, 1, dtype=torch.float32)
    deg.index_add_(0, src, torch.ones_like(w).unsqueeze(-1))
    deg.index_add_(0, dst, torch.ones_like(w).unsqueeze(-1))
    deg = deg.clamp(min=1.0)

    agg = agg / deg  # degree normalization

    old_dim = data.x.size(1)
    data.x = torch.cat([data.x, agg], dim=1)

    print(
        f"[*] augment_with_edge_attr: x_dim {old_dim} → {data.x.size(1)} "
        f"(+{num_relations} from edge_attr aggregation)"
    )
    return data


def set_seed(seed: int = 42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


def get_device():
    return torch.device("cuda" if torch.cuda.is_available() else "cpu")


# -----------------------------
# R-GCN model
# -----------------------------


class HvtRGCN(nn.Module):
    """
    Simple R-GCN-based HVT binary classifier.

    - num_relations = edge_type.max + 1 (hier/fin/comm/ops/ideo)
    """

    def __init__(
        self,
        in_channels: int,
        hidden_channels: int,
        num_relations: int,
        num_layers: int = 2,
        dropout: float = 0.5,
    ):
        super().__init__()
        assert num_layers >= 2, "num_layers must be at least 2."

        self.num_relations = num_relations
        self.dropout = dropout

        self.convs = nn.ModuleList()
        # First layer: in -> hidden
        self.convs.append(
            RGCNConv(in_channels, hidden_channels, num_relations=num_relations)
        )
        # Middle hidden layers
        for _ in range(num_layers - 2):
            self.convs.append(
                RGCNConv(hidden_channels, hidden_channels, num_relations=num_relations)
            )
        # Final projection: hidden -> 1 (logit)
        self.out_lin = nn.Linear(hidden_channels, 1)

    def forward(self, x, edge_index, edge_type):
        h = x
        for conv in self.convs:
            h = conv(h, edge_index, edge_type)
            h = F.relu(h)
            h = F.dropout(h, p=self.dropout, training=self.training)

        logit = self.out_lin(h).view(-1)  # [N]
        return logit


# -----------------------------
# Training / evaluation helpers
# -----------------------------

def train_one_epoch(
    model: nn.Module,
    data: Data,
    optimizer: torch.optim.Optimizer,
    criterion: nn.Module,
    device: torch.device,
) -> float:
    model.train()
    optimizer.zero_grad()

    x = data.x.to(device)
    edge_index = data.edge_index.to(device)
    edge_type = data.edge_type.to(device)
    y_hvt = data.y_hvt.to(device)

    train_mask = data.train_mask.to(device)

    logits = model(x, edge_index, edge_type)  # [N]
    loss = criterion(logits[train_mask], y_hvt[train_mask].float())

    loss.backward()
    optimizer.step()

    return float(loss.item())


@torch.no_grad()
def evaluate(
    model: nn.Module,
    data: Data,
    device: torch.device,
    threshold: float = 0.5,
):
    model.eval()

    x = data.x.to(device)
    edge_index = data.edge_index.to(device)
    edge_type = data.edge_type.to(device)
    y_hvt = data.y_hvt.to(device)

    masks = {
        "train": data.train_mask,
        "val": data.val_mask,
        "test": data.test_mask,
    }

    logits = model(x, edge_index, edge_type)  # [N]
    probs = torch.sigmoid(logits)            # [N]

    all_metrics = {}
    for split, mask in masks.items():
        mask = mask.to(device)
        y_true = y_hvt[mask]
        y_prob = probs[mask]

        if y_true.numel() == 0:
            continue

        y_pred = (y_prob >= threshold).long()

        y_true_np = y_true.cpu().numpy()
        y_pred_np = y_pred.cpu().numpy()
        y_prob_np = y_prob.cpu().numpy()

        acc = accuracy_score(y_true_np, y_pred_np)
        f1 = f1_score(y_true_np, y_pred_np, zero_division=0)

        # AUC can only be computed when both positive and negative labels exist
        try:
            auc = roc_auc_score(y_true_np, y_prob_np)
        except ValueError:
            auc = float("nan")

        all_metrics[split] = {"acc": acc, "f1": f1, "auc": auc}

    return all_metrics


@torch.no_grad()
def collect_probs(model: nn.Module, data: Data, device: torch.device):
    """
    Return a dict of (y_true, y_prob) pairs for train/val/test splits.
    """
    model.eval()

    x = data.x.to(device)
    edge_index = data.edge_index.to(device)
    edge_type = data.edge_type.to(device)
    y_hvt = data.y_hvt.to(device)

    masks = {
        "train": data.train_mask,
        "val": data.val_mask,
        "test": data.test_mask,
    }

    logits = model(x, edge_index, edge_type)
    probs = torch.sigmoid(logits)

    out = {}
    for split, mask in masks.items():
        mask = mask.to(device)
        y_true = y_hvt[mask]
        y_prob = probs[mask]

        if y_true.numel() == 0:
            continue

        out[split] = (y_true.cpu().numpy(), y_prob.cpu().numpy())

    return out


def compute_metrics_at_threshold(y_true, y_prob, thr: float):
    y_pred = (y_prob >= thr).astype(int)
    acc = accuracy_score(y_true, y_pred)
    f1 = f1_score(y_true, y_pred, zero_division=0)
    try:
        auc = roc_auc_score(y_true, y_prob)
    except ValueError:
        auc = float("nan")
    return {"acc": acc, "f1": f1, "auc": auc}


def find_best_threshold_for_f1(y_true, y_prob, num_steps: int = 200):
    """
    Sweep the [0, 1] range into num_steps intervals to find the F1-maximizing threshold.
    """
    best_thr = 0.5
    best_metric = None

    for i in range(num_steps + 1):
        thr = i / num_steps
        metrics = compute_metrics_at_threshold(y_true, y_prob, thr)
        if best_metric is None or metrics["f1"] > best_metric["f1"]:
            best_metric = metrics
            best_thr = thr

    return best_thr, best_metric


# -----------------------------
# main
# -----------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Train R-GCN baseline for high_value_target node classification."
    )
    parser.add_argument(
        "--data_path",
        type=str,
        required=True,
        help="Path to pyg_data.pt (output of build_pyg_dataset.py)",
    )
    parser.add_argument(
        "--hidden_dim",
        type=int,
        default=64,
        help="Hidden dimension size (default: 64)",
    )
    parser.add_argument(
        "--num_layers",
        type=int,
        default=2,
        help="Number of R-GCN layers (default: 2)",
    )
    parser.add_argument(
        "--dropout",
        type=float,
        default=0.5,
        help="Dropout probability (default: 0.5)",
    )
    parser.add_argument(
        "--lr",
        type=float,
        default=1e-3,
        help="Learning rate (default: 1e-3)",
    )
    parser.add_argument(
        "--weight_decay",
        type=float,
        default=1e-4,
        help="Weight decay (L2 regularization, default: 1e-4)",
    )
    parser.add_argument(
        "--epochs",
        type=int,
        default=200,
        help="Number of training epochs (default: 200)",
    )
    parser.add_argument(
        "--patience",
        type=int,
        default=30,
        help="Early stopping patience in epochs (default: 30; 0 or negative disables early stopping)",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed (default: 42)",
    )
    parser.add_argument(
        "--pos_weight",
        type=float,
        default=1.0,
        help="Positive class weight for BCEWithLogitsLoss (default: 1.0 = no reweighting)",
    )


    parser.add_argument(
        "--edge_attr_transform",
        type=str,
        default="auto",
        choices=["auto", "none", "log1p"],
        help="Transform for edge_attr aggregation features. Use 'auto' to log1p only if heavy-tailed (recommended).",
    )
    parser.add_argument("--edge_attr_auto_q", type=float, default=0.99)
    parser.add_argument("--edge_attr_auto_thresh", type=float, default=20.0)
    parser.add_argument(
        "--auto_pos_weight",
        action="store_true",
        help="If set, compute pos_weight from the training split (overrides --pos_weight).",
    )
    args = parser.parse_args()

    set_seed(args.seed)
    device = get_device()
    print(f"\n[*] Using device: {device}")

    if not os.path.exists(args.data_path):
        raise FileNotFoundError(f"Data not found at: {args.data_path}")

    print("[*] Loading PyG Data from:", args.data_path)
    out_dir = os.path.dirname(args.data_path)
    best_model_path = os.path.join(out_dir, "hvt_model_best.pt")
    data: Data = load_pyg_data(args.data_path, map_location="cpu")
    # Resolve a fixed edge_attr transform once for consistency
    edge_attr_transform = "none"
    if hasattr(data, "edge_attr") and data.edge_attr is not None:
        ea_np = data.edge_attr.view(-1).cpu().numpy()
        edge_attr_transform = resolve_edge_attr_transform_np(
            ea_np, mode=args.edge_attr_transform, q=args.edge_attr_auto_q, thresh=args.edge_attr_auto_thresh
        )
    print(f"[*] edge_attr_transform resolved: {edge_attr_transform}")
    # Node feature augmentation with edge_attr
    data = augment_with_edge_attr(data, edge_attr_transform=edge_attr_transform)

    print(data)

    in_channels = data.x.size(1)
    num_relations = int(data.edge_type.max().item()) + 1

    model = HvtRGCN(
        in_channels=in_channels,
        hidden_channels=args.hidden_dim,
        num_relations=num_relations,
        num_layers=args.num_layers,
        dropout=args.dropout,
    ).to(device)

    # Set pos_weight
    # If the HVT ratio is ~5%, tuning between 10 and 20 can work reasonably well.
    pos_w = torch.tensor([args.pos_weight], device=device)
    criterion = nn.BCEWithLogitsLoss(pos_weight=pos_w)

    optimizer = torch.optim.Adam(
        model.parameters(), lr=args.lr, weight_decay=args.weight_decay
    )

    best_val_auc = -1.0
    best_test_metrics_at_05 = None
    best_epoch = 0
    epochs_no_improve = 0

    # -------------------------
    # Monitor training with the default threshold=0.5
    # -------------------------
    for epoch in range(1, args.epochs + 1):
        loss = train_one_epoch(model, data, optimizer, criterion, device)
        metrics = evaluate(model, data, device, threshold=0.5)

        train_m = metrics.get("train", {})
        val_m = metrics.get("val", {})
        test_m = metrics.get("test", {})

        val_auc = val_m.get("auc", float("nan"))

        improved = (not np.isnan(val_auc)) and (val_auc > best_val_auc)
        if improved:
            best_val_auc = val_auc
            best_test_metrics_at_05 = test_m
            best_epoch = epoch
            epochs_no_improve = 0
            # Save best model checkpoint
            try:
                torch.save(model.state_dict(), best_model_path)
            except Exception as e:
                print(f"[!] Failed to save best model checkpoint to {best_model_path}: {e}")
        else:
            epochs_no_improve += 1

        if epoch % 10 == 0 or epoch == 1 or epoch == args.epochs:
            print(
                f"[Epoch {epoch:03d}] "
                f"loss={loss:.4f} | "
                f"train_acc={train_m.get('acc', float('nan')):.3f}, "
                f"val_acc={val_m.get('acc', float('nan')):.3f}, "
                f"val_auc={val_m.get('auc', float('nan')):.3f}"
            )

        if args.patience > 0 and epochs_no_improve >= args.patience:
            print(
                f"[EarlyStopping] No val AUC improvement for {args.patience} epochs. "
                f"Stopping at epoch {epoch}."
            )
            break

    print("\n[*] Training finished.")
    print(f"[0.5 threshold] Best val AUC: {best_val_auc:.3f} (epoch={best_epoch})")
    if best_test_metrics_at_05 is not None:
        print("[0.5 threshold] Corresponding test metrics at best val AUC:")
        print(
            f"  test_acc = {best_test_metrics_at_05.get('acc', float('nan')):.3f}, "
            f"test_f1 = {best_test_metrics_at_05.get('f1', float('nan')):.3f}, "
            f"test_auc = {best_test_metrics_at_05.get('auc', float('nan')):.3f}"
        )

    # -------------------------
    # Validation-set threshold sweep (maximize F1)
    # -------------------------
    # Load the best model checkpoint if available
    if os.path.exists(best_model_path) and best_epoch > 0:
        print(f"[*] Loading best model checkpoint from: {best_model_path} (epoch={best_epoch})")
        model.load_state_dict(torch.load(best_model_path, map_location=device))
    else:
        print("[!] Best model checkpoint not found. Using last-epoch model for threshold sweep.")

    print("\n[*] Sweeping threshold on validation set to maximize F1...")

    probs_dict = collect_probs(model, data, device)
    val_y, val_p = probs_dict["val"]

    best_thr, best_val_metrics = find_best_threshold_for_f1(val_y, val_p, num_steps=100)
    print(
        f"[*] Best threshold (val F1): {best_thr:.3f} | "
        f"val_acc={best_val_metrics['acc']:.3f}, "
        f"val_f1={best_val_metrics['f1']:.3f}, "
        f"val_auc={best_val_metrics['auc']:.3f}"
    )

    # Recompute train/test performance with that threshold
    train_y, train_p = probs_dict["train"]
    test_y, test_p = probs_dict["test"]

    train_m_best = compute_metrics_at_threshold(train_y, train_p, best_thr)
    test_m_best = compute_metrics_at_threshold(test_y, test_p, best_thr)

    print("\n[*] Metrics with best validation F1 threshold:")
    print(
        f"  [Train] acc={train_m_best['acc']:.3f}, "
        f"f1={train_m_best['f1']:.3f}, "
        f"auc={train_m_best['auc']:.3f}"
    )
    print(
        f"  [Test]  acc={test_m_best['acc']:.3f}, "
        f"f1={test_m_best['f1']:.3f}, "
        f"auc={test_m_best['auc']:.3f}"
    )

    out_dir = os.path.dirname(args.data_path)
    metrics_path = os.path.join(out_dir, "hvt_metrics.json")

    def _to_float_dict(d):
        return {k: float(v) for k, v in d.items()}

    result = {
        "task": "hvt_single",
        "data_path": args.data_path,
        "seed": args.seed,
        "hidden_dim": args.hidden_dim,
        "num_layers": args.num_layers,
        "dropout": args.dropout,
        "pos_weight": float(args.pos_weight),
        "best_threshold": float(best_thr),
        "val_best": _to_float_dict(best_val_metrics),
        "train": _to_float_dict(train_m_best),
        "test": _to_float_dict(test_m_best),
    }

    with open(metrics_path, "w") as f:
        json.dump(result, f, indent=2)

    print(f"[*] Saved HVT metrics to: {metrics_path}")


if __name__ == "__main__":
    main()
